server:
  port: 9093

logging:
  level:
    org.springframework.security: trace

spring:
  datasource:
    url: jdbc:h2:mem:testing_authorization
    #url: jdbc:h2:file:/data/demo
    username: testing_connection
    password: G4s7Zd6h2
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
      #ddl-auto: create/validate/update
    defer-datasource-initialization: true #????? data.sql ?????????? ????? ddl-auto: create